package it.unirc.pwm.EntityMappingHB;
// Generated 22 mar 2022, 17:25:01 by Hibernate Tools 5.5.7.Final

/**
 * Amministratore generated by hbm2java
 */
public class Amministratore implements java.io.Serializable {

	private int idcliente;
	private Cliente cliente;
	private String nomeamministratore;
	private String cognomeamministratore;
	private String codicefiscale;

	public Amministratore() {
	}

	public Amministratore(Cliente cliente, String nomeamministratore, String cognomeamministratore,
			String codicefiscale) {
		this.cliente = cliente;
		this.nomeamministratore = nomeamministratore;
		this.cognomeamministratore = cognomeamministratore;
		this.codicefiscale = codicefiscale;
	}

	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getNomeamministratore() {
		return this.nomeamministratore;
	}

	public void setNomeamministratore(String nomeamministratore) {
		this.nomeamministratore = nomeamministratore;
	}

	public String getCognomeamministratore() {
		return this.cognomeamministratore;
	}

	public void setCognomeamministratore(String cognomeamministratore) {
		this.cognomeamministratore = cognomeamministratore;
	}

	public String getCodicefiscale() {
		return this.codicefiscale;
	}

	public void setCodicefiscale(String codicefiscale) {
		this.codicefiscale = codicefiscale;
	}

}
