package it.unirc.pwm.EntityMappingHB;
// Generated 22 mar 2022, 17:25:01 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Cartadicredito generated by hbm2java
 */
public class Cartadicredito implements java.io.Serializable {

	private int idordine;
	private Date datapagamento;
	private Double importo;
	private String nomeintestatario;
	private String cognomeintestatario;

	public Cartadicredito() {
	}

	public Cartadicredito(int idordine) {
		this.idordine = idordine;
	}

	public Cartadicredito(int idordine, Date datapagamento, Double importo, String nomeintestatario,
			String cognomeintestatario) {
		this.idordine = idordine;
		this.datapagamento = datapagamento;
		this.importo = importo;
		this.nomeintestatario = nomeintestatario;
		this.cognomeintestatario = cognomeintestatario;
	}

	public int getIdordine() {
		return this.idordine;
	}

	public void setIdordine(int idordine) {
		this.idordine = idordine;
	}

	public Date getDatapagamento() {
		return this.datapagamento;
	}

	public void setDatapagamento(Date datapagamento) {
		this.datapagamento = datapagamento;
	}

	public Double getImporto() {
		return this.importo;
	}

	public void setImporto(Double importo) {
		this.importo = importo;
	}

	public String getNomeintestatario() {
		return this.nomeintestatario;
	}

	public void setNomeintestatario(String nomeintestatario) {
		this.nomeintestatario = nomeintestatario;
	}

	public String getCognomeintestatario() {
		return this.cognomeintestatario;
	}

	public void setCognomeintestatario(String cognomeintestatario) {
		this.cognomeintestatario = cognomeintestatario;
	}

}
