package it.unirc.pwm.EntityMappingHB;
// Generated 22 mar 2022, 17:25:01 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Contrassegno generated by hbm2java
 */
public class Contrassegno implements java.io.Serializable {

	private int idordine;
	private Date datapagamento;
	private double importo;
	private String firmatario;
	private String imgfirma;

	public Contrassegno() {
	}

	public Contrassegno(int idordine, Date datapagamento, double importo, String firmatario, String imgfirma) {
		this.idordine = idordine;
		this.datapagamento = datapagamento;
		this.importo = importo;
		this.firmatario = firmatario;
		this.imgfirma = imgfirma;
	}

	public int getIdordine() {
		return this.idordine;
	}

	public void setIdordine(int idordine) {
		this.idordine = idordine;
	}

	public Date getDatapagamento() {
		return this.datapagamento;
	}

	public void setDatapagamento(Date datapagamento) {
		this.datapagamento = datapagamento;
	}

	public double getImporto() {
		return this.importo;
	}

	public void setImporto(double importo) {
		this.importo = importo;
	}

	public String getFirmatario() {
		return this.firmatario;
	}

	public void setFirmatario(String firmatario) {
		this.firmatario = firmatario;
	}

	public String getImgfirma() {
		return this.imgfirma;
	}

	public void setImgfirma(String imgfirma) {
		this.imgfirma = imgfirma;
	}

}
