package it.unirc.pwm.EntityMappingHB;
// Generated 22 mar 2022, 17:25:01 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * CorriereExp generated by hbm2java
 */
public class CorriereExp implements java.io.Serializable {

	private int idordine;
	private Spedizione spedizione;
	private int spesaspedizionExp;
	private Date dataspedizioneExp;
	private Date dataconsegnaExp;

	public CorriereExp() {
	}

	public CorriereExp(Spedizione spedizione, int spesaspedizionExp, Date dataspedizioneExp, Date dataconsegnaExp) {
		this.spedizione = spedizione;
		this.spesaspedizionExp = spesaspedizionExp;
		this.dataspedizioneExp = dataspedizioneExp;
		this.dataconsegnaExp = dataconsegnaExp;
	}

	public int getIdordine() {
		return this.idordine;
	}

	public void setIdordine(int idordine) {
		this.idordine = idordine;
	}

	public Spedizione getSpedizione() {
		return this.spedizione;
	}

	public void setSpedizione(Spedizione spedizione) {
		this.spedizione = spedizione;
	}

	public int getSpesaspedizionExp() {
		return this.spesaspedizionExp;
	}

	public void setSpesaspedizionExp(int spesaspedizionExp) {
		this.spesaspedizionExp = spesaspedizionExp;
	}

	public Date getDataspedizioneExp() {
		return this.dataspedizioneExp;
	}

	public void setDataspedizioneExp(Date dataspedizioneExp) {
		this.dataspedizioneExp = dataspedizioneExp;
	}

	public Date getDataconsegnaExp() {
		return this.dataconsegnaExp;
	}

	public void setDataconsegnaExp(Date dataconsegnaExp) {
		this.dataconsegnaExp = dataconsegnaExp;
	}

}
