package it.unirc.pwm.EntityMappingHB;
// Generated 22 mar 2022, 17:25:01 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Prodotto generated by hbm2java
 */
public class Prodotto implements java.io.Serializable {

	private Integer idprodotto;
	private Categoria categoria;
	private String nomep;
	private String immaginep;
	private String descrizionep;
	private double prezzo;
	private Set ordines = new HashSet(0);

	public Prodotto() {
	}

	public Prodotto(Categoria categoria, String nomep, String immaginep, String descrizionep, double prezzo) {
		this.categoria = categoria;
		this.nomep = nomep;
		this.immaginep = immaginep;
		this.descrizionep = descrizionep;
		this.prezzo = prezzo;
	}

	public Prodotto(Categoria categoria, String nomep, String immaginep, String descrizionep, double prezzo,
			Set ordines) {
		this.categoria = categoria;
		this.nomep = nomep;
		this.immaginep = immaginep;
		this.descrizionep = descrizionep;
		this.prezzo = prezzo;
		this.ordines = ordines;
	}

	public Integer getIdprodotto() {
		return this.idprodotto;
	}

	public void setIdprodotto(Integer idprodotto) {
		this.idprodotto = idprodotto;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getNomep() {
		return this.nomep;
	}

	public void setNomep(String nomep) {
		this.nomep = nomep;
	}

	public String getImmaginep() {
		return this.immaginep;
	}

	public void setImmaginep(String immaginep) {
		this.immaginep = immaginep;
	}

	public String getDescrizionep() {
		return this.descrizionep;
	}

	public void setDescrizionep(String descrizionep) {
		this.descrizionep = descrizionep;
	}

	public double getPrezzo() {
		return this.prezzo;
	}

	public void setPrezzo(double prezzo) {
		this.prezzo = prezzo;
	}

	public Set getOrdines() {
		return this.ordines;
	}

	public void setOrdines(Set ordines) {
		this.ordines = ordines;
	}

}
