package it.unirc.pwm.EntityMappingHB;
// Generated 22 mar 2022, 17:25:01 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Spedizione generated by hbm2java
 */
public class Spedizione implements java.io.Serializable {

	private int idordine;
	private Ordine ordine;
	private String nomecorriere;
	private Date datapartenza;
	private Date dataconsegna;
	private Corriere corriere;
	private CorriereExp corriereExp;

	public Spedizione() {
	}

	public Spedizione(Ordine ordine, String nomecorriere, Date datapartenza, Date dataconsegna) {
		this.ordine = ordine;
		this.nomecorriere = nomecorriere;
		this.datapartenza = datapartenza;
		this.dataconsegna = dataconsegna;
	}

	public Spedizione(Ordine ordine, String nomecorriere, Date datapartenza, Date dataconsegna, Corriere corriere,
			CorriereExp corriereExp) {
		this.ordine = ordine;
		this.nomecorriere = nomecorriere;
		this.datapartenza = datapartenza;
		this.dataconsegna = dataconsegna;
		this.corriere = corriere;
		this.corriereExp = corriereExp;
	}

	public int getIdordine() {
		return this.idordine;
	}

	public void setIdordine(int idordine) {
		this.idordine = idordine;
	}

	public Ordine getOrdine() {
		return this.ordine;
	}

	public void setOrdine(Ordine ordine) {
		this.ordine = ordine;
	}

	public String getNomecorriere() {
		return this.nomecorriere;
	}

	public void setNomecorriere(String nomecorriere) {
		this.nomecorriere = nomecorriere;
	}

	public Date getDatapartenza() {
		return this.datapartenza;
	}

	public void setDatapartenza(Date datapartenza) {
		this.datapartenza = datapartenza;
	}

	public Date getDataconsegna() {
		return this.dataconsegna;
	}

	public void setDataconsegna(Date dataconsegna) {
		this.dataconsegna = dataconsegna;
	}

	public Corriere getCorriere() {
		return this.corriere;
	}

	public void setCorriere(Corriere corriere) {
		this.corriere = corriere;
	}

	public CorriereExp getCorriereExp() {
		return this.corriereExp;
	}

	public void setCorriereExp(CorriereExp corriereExp) {
		this.corriereExp = corriereExp;
	}

}
